build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
images:
- dockerfile_path: prow/Dockerfile
  to: ocp-qe-perfscale-ci-uperf-npt
promotion:
  namespace: ci
  tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: ocp-qe-perfscale-uperf-npt-gcp
  cron: 0 9 * * 4
  steps:
    cluster_profile: gcp-qe
    env:
      WORKER_REPLICA_COUNT: "5"
    post:
    - chain: ipi-gcp-post
    pre:
    - chain: ipi-gcp-pre
    - chain: workers-scale
    - chain: create-infra-move-ingress-monitoring-registry
    workflow: openshift-qe-uperf-npt
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: uperf-npt-ocp14
