build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
images:
- dockerfile_path: prow/Dockerfile
  to: ocp-qe-perfscale-ci-rosa-4.13-nightly
promotion:
  namespace: ci
  tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: perfscale-rosa-multiaz-data-path-9nodes-periodic
  cron: 0 7 * * 1
  steps:
    cluster_profile: aws-qe
    env:
      CHANNEL_GROUP: nightly
      COMPUTE_MACHINE_TYPE: m5.xlarge
      CONFIG: config/standard-classic-rosa.yml
      ENABLE_AUTOSCALING: "false"
      MULTI_AZ: "true"
      OPENSHIFT_VERSION: "4.13"
      REPLICAS: "9"
    test:
    - chain: openshift-qe-data-path-tests
    workflow: rosa-aws-sts
  timeout: 5h0m0s
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: rosa-4.13-nightly-x86
